
-- ============================================
-- 1. USERS TABLE
-- ============================================

CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) DEFAULT 'user',
  security_question TEXT,
  security_answer TEXT,
  failed_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMP WITH TIME ZONE,
  join_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  last_active TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);

-- ============================================
-- 2. USER GLOBAL STATS TABLE
-- ============================================
CREATE TABLE public.user_global_stats (
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  total_points BIGINT DEFAULT 0,
  total_questions BIGINT DEFAULT 0,
  daily_streak INTEGER DEFAULT 0,
  avg_score NUMERIC(5,2) DEFAULT 0.0,
  hours_played INTEGER DEFAULT 0,
  current_rank INTEGER
);

-- ============================================
-- 3. USER GAME MODE STATS TABLE
-- ============================================
CREATE TABLE public.user_game_mode_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  game_mode TEXT NOT NULL,
  games_played INTEGER DEFAULT 0,
  best_score INTEGER DEFAULT 0,
  current_streak INTEGER DEFAULT 0,
  success_rate NUMERIC(5,2),
  CONSTRAINT unique_user_game_mode UNIQUE (user_id, game_mode)
);

CREATE INDEX IF NOT EXISTS idx_game_mode_stats_user ON public.user_game_mode_stats(user_id);
CREATE INDEX IF NOT EXISTS idx_game_mode_stats_mode ON public.user_game_mode_stats(game_mode);

-- ============================================
-- 4. GAME SESSIONS TABLE
-- ============================================
CREATE TABLE public.game_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  game_mode TEXT NOT NULL,
  score INTEGER NOT NULL,
  played_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_game_sessions_user ON public.game_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_game_sessions_played_at ON public.game_sessions(played_at);

-- ============================================
-- 5. QUESTIONS TABLE
-- ============================================
CREATE TABLE public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  correct INTEGER NOT NULL,
  difficulty INTEGER DEFAULT 1,
  points INTEGER DEFAULT 10,
  fact TEXT
);

CREATE INDEX IF NOT EXISTS idx_questions_category ON public.questions(category);
CREATE INDEX IF NOT EXISTS idx_questions_difficulty ON public.questions(difficulty);

-- ============================================
-- 6. GUESS PLAYER QUESTIONS TABLE
-- ============================================
CREATE TABLE public.guess_player_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  clues JSONB NOT NULL,
  stats TEXT
);

-- ============================================
-- 7. MVP WINNERS TABLE
-- ============================================
CREATE TABLE public.mvp_winners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  team TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mvp_winners_year ON public.mvp_winners(year);

-- ============================================
-- 8. ACHIEVEMENTS TABLE
-- ============================================
CREATE TABLE public.achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT
);

-- ============================================
-- 9. USER ACHIEVEMENTS TABLE
-- ============================================
CREATE TABLE public.user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  achievement_id BIGINT REFERENCES public.achievements(id) ON DELETE CASCADE NOT NULL,
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  CONSTRAINT unique_user_achievement UNIQUE (user_id, achievement_id)
);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON public.user_achievements(user_id);

-- ============================================
-- 10. PASSWORD RESETS TABLE
-- ============================================
CREATE TABLE public.password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_password_resets_token ON public.password_resets(token);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON public.password_resets(user_id);

