
-- ============================================
-- 1. TRIVIA & HISTORY QUESTIONS (40 entries)
-- ============================================

INSERT INTO public.questions (category, question, options, correct, difficulty, points, fact) VALUES
-- Easy Questions (1-15)
('Trivia', 'Who holds the NBA record for most career points scored?', '["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"]', 0, 1, 10, 'LeBron James surpassed Kareem Abdul-Jabbar''s record in February 2023, becoming the all-time leading scorer.'),
('History', 'Which team has won the most NBA championships?', '["Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors"]', 0, 1, 10, 'The Boston Celtics have won 18 NBA championships, the most in league history.'),
('History', 'How many championships did Michael Jordan win with the Chicago Bulls?', '["5", "6", "7", "8"]', 1, 1, 10, 'Michael Jordan won 6 NBA championships with the Bulls in two three-peats (1991-93, 1996-98).'),
('Trivia', 'How many players from one team are allowed on the court at once?', '["4", "5", "6", "7"]', 1, 1, 10, 'Five players per team are allowed on the court during play in regulation basketball.'),
('History', 'Who was the first overall pick in the 2003 NBA Draft?', '["LeBron James", "Carmelo Anthony", "Dwyane Wade", "Chris Bosh"]', 0, 1, 10, 'LeBron James was selected first overall by the Cleveland Cavaliers in the legendary 2003 draft class.'),
('Trivia', 'Who scored 100 points in a single NBA game?', '["Wilt Chamberlain", "Kobe Bryant", "Michael Jordan", "Elgin Baylor"]', 0, 1, 10, 'Wilt Chamberlain scored 100 points for the Philadelphia Warriors against the New York Knicks on March 2, 1962.'),
('Trivia', 'Which player is known as "The Greek Freak"?', '["Giannis Antetokounmpo", "Luka Doncic", "Nikola Jokic", "Joel Embiid"]', 0, 1, 10, 'Giannis Antetokounmpo earned this nickname due to his Greek heritage and exceptional athleticism.'),
('Trivia', 'How many points is a free throw worth?', '["1", "2", "3", "4"]', 0, 1, 10, 'A successful free throw is worth 1 point and is taken from the free-throw line after a foul.'),
('History', 'What team did Kobe Bryant play his entire career with?', '["Los Angeles Lakers", "Boston Celtics", "Miami Heat", "Chicago Bulls"]', 0, 1, 10, 'Kobe Bryant spent all 20 seasons of his NBA career with the Lakers from 1996 to 2016.'),
('Trivia', 'Who is known as "King James"?', '["LeBron James", "James Harden", "James Worthy", "Jimmy Butler"]', 0, 1, 10, 'LeBron James has been nicknamed "King James" since his high school days due to his dominant play.'),
('Trivia', 'Who holds the record for most assists in NBA history?', '["John Stockton", "Magic Johnson", "Jason Kidd", "Chris Paul"]', 0, 1, 10, 'John Stockton recorded 15,806 assists during his career, a record that still stands today.'),
('History', 'Which team won the first NBA championship in 1947?', '["Philadelphia Warriors", "New York Knicks", "Boston Celtics", "Minneapolis Lakers"]', 0, 1, 10, 'The Philadelphia Warriors defeated the Chicago Stags 4-1 to win the inaugural BAA (later NBA) championship.'),
('Trivia', 'How many seconds does a team have to attempt a shot (shot clock)?', '["20", "24", "30", "35"]', 1, 1, 10, 'The NBA shot clock is 24 seconds, requiring teams to attempt a shot within that timeframe.'),
('History', 'What number did Michael Jordan famously wear?', '["23", "24", "32", "33"]', 0, 1, 10, 'Michael Jordan wore #23 for most of his career, making it one of the most iconic jersey numbers in sports.'),
('Trivia', 'Which player has won the most MVP awards?', '["Kareem Abdul-Jabbar", "Michael Jordan", "LeBron James", "Bill Russell"]', 0, 1, 10, 'Kareem Abdul-Jabbar won 6 MVP awards during his illustrious career, the most in NBA history.'),

-- Medium Questions (16-30)
('Trivia', 'Who holds the record for most rebounds in a single game?', '["Wilt Chamberlain", "Bill Russell", "Dennis Rodman", "Shaquille O''Neal"]', 0, 2, 20, 'Wilt Chamberlain grabbed 55 rebounds in a game on November 24, 1960.'),
('History', 'What year did the NBA introduce the three-point line?', '["1977", "1979", "1981", "1985"]', 1, 2, 20, 'The NBA adopted the three-point line in the 1979-80 season, revolutionizing offensive strategy.'),
('History', 'Who was the first international player to be drafted #1 overall?', '["Hakeem Olajuwon", "Yao Ming", "Andrew Bogut", "Andrea Bargnani"]', 0, 2, 20, 'Hakeem Olajuwon from Nigeria was selected first overall by Houston in 1984, though he played college ball at Houston.'),
('Trivia', 'Who has the most triple-doubles in NBA history?', '["Russell Westbrook", "Oscar Robertson", "Magic Johnson", "LeBron James"]', 0, 2, 20, 'Russell Westbrook holds the record with over 200 career triple-doubles and counting.'),
('History', 'What team drafted Kobe Bryant before he was traded to the Lakers?', '["Charlotte Hornets", "New Jersey Nets", "Philadelphia 76ers", "Washington Bullets"]', 0, 2, 20, 'The Charlotte Hornets drafted Kobe 13th overall in 1996 before trading him to the Lakers.'),
('Trivia', 'Who scored the most points in a single season?', '["Wilt Chamberlain", "Michael Jordan", "Kobe Bryant", "James Harden"]', 0, 2, 20, 'Wilt Chamberlain scored 4,029 points in the 1961-62 season, averaging 50.4 points per game.'),
('History', 'Which team had a 73-9 record in the 2015-16 season?', '["Golden State Warriors", "Chicago Bulls", "Los Angeles Lakers", "San Antonio Spurs"]', 0, 2, 20, 'The Warriors broke the Bulls'' 72-10 record but lost in the NBA Finals to Cleveland.'),
('Trivia', 'Who was the youngest player to score 10,000 career points?', '["LeBron James", "Kobe Bryant", "Kevin Durant", "Carmelo Anthony"]', 0, 2, 20, 'LeBron James reached 10,000 points at 23 years and 59 days old in 2008.'),
('Trivia', 'What player holds the record for most steals in NBA history?', '["John Stockton", "Jason Kidd", "Chris Paul", "Gary Payton"]', 0, 2, 20, 'John Stockton recorded 3,265 steals during his 19-year career with the Utah Jazz.'),
('History', 'Which player scored 81 points in a game in 2006?', '["Kobe Bryant", "Allen Iverson", "Tracy McGrady", "Dwyane Wade"]', 0, 2, 20, 'Kobe Bryant scored 81 points against the Toronto Raptors on January 22, 2006, the second-highest single-game total ever.'),
('History', 'What team did Shaquille O''Neal win his first championship with?', '["Los Angeles Lakers", "Miami Heat", "Orlando Magic", "Boston Celtics"]', 0, 2, 20, 'Shaq won his first of four championships with the Lakers in 2000, starting a three-peat.'),
('Trivia', 'Who holds the record for most blocks in NBA history?', '["Hakeem Olajuwon", "Dikembe Mutombo", "Kareem Abdul-Jabbar", "Mark Eaton"]', 0, 2, 20, 'Hakeem Olajuwon recorded 3,830 blocks during his Hall of Fame career.'),
('History', 'Which coach has won the most NBA championships?', '["Phil Jackson", "Red Auerbach", "Pat Riley", "Gregg Popovich"]', 0, 2, 20, 'Phil Jackson won 11 championships as a coach - 6 with the Bulls and 5 with the Lakers.'),
('Trivia', 'What player was known as "The Mailman"?', '["Karl Malone", "Charles Barkley", "Patrick Ewing", "David Robinson"]', 0, 2, 20, 'Karl Malone earned this nickname because he always delivered, playing in Utah for 18 seasons.'),
('Trivia', 'Who has the most career three-pointers made?', '["Stephen Curry", "Ray Allen", "Reggie Miller", "James Harden"]', 0, 2, 20, 'Stephen Curry surpassed Ray Allen to become the all-time leader in three-pointers made.'),

-- Hard Questions (31-40)
('Trivia', 'Who is the only player to average a triple-double for an entire season besides Russell Westbrook?', '["Oscar Robertson", "Magic Johnson", "Wilt Chamberlain", "Larry Bird"]', 0, 3, 30, 'Oscar Robertson averaged a triple-double in the 1961-62 season (30.8 PPG, 12.5 RPG, 11.4 APG).'),
('History', 'What year did the NBA merge with the ABA?', '["1974", "1976", "1978", "1980"]', 1, 3, 30, 'The NBA and ABA merged in 1976, bringing in teams like the Spurs, Nuggets, Pacers, and Nets.'),
('Trivia', 'Who holds the record for most consecutive games with a made three-pointer?', '["Stephen Curry", "Kyle Korver", "James Harden", "Damian Lillard"]', 0, 3, 30, 'Stephen Curry made at least one three-pointer in 268 consecutive games from 2018 to 2021.'),
('History', 'Which player won Finals MVP despite being on the losing team?', '["Jerry West", "LeBron James", "Allen Iverson", "Charles Barkley"]', 0, 3, 30, 'Jerry West won Finals MVP in 1969 despite the Lakers losing to the Celtics - the only time this has happened.'),
('Trivia', 'What is the most points scored by a player in their NBA debut?', '["43", "48", "53", "58"]', 2, 3, 30, 'Wilt Chamberlain scored 43 points and grabbed 28 rebounds in his NBA debut on October 24, 1959.'),
('History', 'Who was the last player to win back-to-back MVP awards before Giannis?', '["Stephen Curry", "LeBron James", "Steve Nash", "Tim Duncan"]', 0, 3, 30, 'Stephen Curry won consecutive MVPs in 2015 and 2016, with the latter being unanimous.'),
('Trivia', 'What player has the most 60-point games in NBA history?', '["Wilt Chamberlain", "Kobe Bryant", "Michael Jordan", "James Harden"]', 0, 3, 30, 'Wilt Chamberlain had 32 games of 60+ points, far more than any other player in history.'),
('History', 'Which team retired the number 23 for Michael Jordan despite him never playing for them?', '["Miami Heat", "Chicago Bulls", "Washington Wizards", "Charlotte Hornets"]', 0, 3, 30, 'The Miami Heat retired #23 in honor of Michael Jordan as a tribute to his impact on basketball.'),
('Trivia', 'Who is the oldest player to score 50+ points in an NBA game?', '["Jamal Crawford", "Michael Jordan", "Kobe Bryant", "Vince Carter"]', 0, 3, 30, 'Jamal Crawford scored 51 points at age 39 years and 20 days in 2019 while playing for the Phoenix Suns.'),
('History', 'What team won the NBA championship in the lockout-shortened 1999 season?', '["San Antonio Spurs", "Los Angeles Lakers", "Chicago Bulls", "Utah Jazz"]', 0, 3, 30, 'The Spurs won their first championship in 1999, defeating the Knicks 4-1 in the Finals.');

-- ============================================
-- 2. GUESS THE PLAYER QUESTIONS (40 entries)
-- ============================================

INSERT INTO public.guess_player_questions (first_name, last_name, clues, stats) VALUES
('Michael', 'Jordan', '["Won 6 NBA championships", "5-time MVP", "Played for the Chicago Bulls", "Known for legendary dunk contests", "Wore #23"]', '30.1 PPG, 6.2 RPG, 5.3 APG career average'),
('LeBron', 'James', '["All-time leading scorer", "4 NBA championships", "Played for Cavs, Heat, Lakers", "Known as King James", "4-time MVP"]', '27.2 PPG, 7.5 RPG, 7.3 APG career average'),
('Kobe', 'Bryant', '["5 NBA championships", "Scored 81 points in a game", "Played entire career with Lakers", "18-time All-Star", "Known as Black Mamba"]', '25.0 PPG, 5.2 RPG, 4.7 APG career average'),
('Magic', 'Johnson', '["5 NBA championships", "3-time MVP", "Legendary Lakers point guard", "6 foot 9 tall point guard", "Won Finals MVP as a rookie"]', '19.5 PPG, 7.2 RPG, 11.2 APG career average'),
('Larry', 'Bird', '["3 NBA championships", "3 consecutive MVPs (1984-86)", "Boston Celtics legend", "One of the best shooters ever", "12-time All-Star"]', '24.3 PPG, 10.0 RPG, 6.3 APG career average'),
('Kareem', 'Abdul-Jabbar', '["6 NBA championships", "6-time MVP", "Famous for skyhook shot", "All-time leading scorer for 39 years", "Played for Bucks and Lakers"]', '24.6 PPG, 11.2 RPG, 3.6 APG career average'),
('Stephen', 'Curry', '["4 NBA championships", "All-time three-point leader", "2-time MVP", "Changed the game with shooting", "Golden State Warriors legend"]', '24.8 PPG, 4.7 RPG, 6.4 APG career average'),
('Tim', 'Duncan', '["5 NBA championships", "2-time MVP", "Played entire career with Spurs", "Known as The Big Fundamental", "15-time All-Star"]', '19.0 PPG, 10.8 RPG, 3.0 APG career average'),
('Shaquille', 'O''Neal', '["4 NBA championships", "3 consecutive Finals MVPs", "Dominant center", "Played for 6 teams", "15-time All-Star"]', '23.7 PPG, 10.9 RPG, 2.5 APG career average'),
('Wilt', 'Chamberlain', '["Scored 100 points in a game", "2 NBA championships", "Averaged 50.4 PPG in a season", "4-time MVP", "Dominant center of the 1960s"]', '30.1 PPG, 22.9 RPG, 4.4 APG career average'),
('Bill', 'Russell', '["11 NBA championships", "5-time MVP", "Celtics dynasty leader", "Greatest winner in NBA history", "12-time All-Star"]', '15.1 PPG, 22.5 RPG, 4.3 APG career average'),
('Hakeem', 'Olajuwon', '["2 NBA championships", "MVP in 1994", "Dream Shake signature move", "3,830 career blocks", "Rockets legend"]', '21.8 PPG, 11.1 RPG, 2.5 APG career average'),
('Kevin', 'Durant', '["2 NBA championships", "2014 MVP", "4-time scoring champion", "Over 7 feet tall", "Known for incredible scoring ability"]', '27.3 PPG, 7.1 RPG, 4.4 APG career average'),
('Giannis', 'Antetokounmpo', '["2021 NBA champion", "2-time MVP", "Known as The Greek Freak", "From Greece", "Bucks franchise player"]', '22.6 PPG, 9.9 RPG, 4.8 APG career average'),
('Dirk', 'Nowitzki', '["2011 NBA champion", "2007 MVP", "Played 21 seasons with Mavericks", "From Germany", "Famous fadeaway shot"]', '20.7 PPG, 7.5 RPG, 2.4 APG career average'),
('Charles', 'Barkley', '["1993 MVP", "Known as Sir Charles", "Never won a championship", "Dominant power forward", "11-time All-Star"]', '22.1 PPG, 11.7 RPG, 3.9 APG career average'),
('Allen', 'Iverson', '["2001 MVP", "11-time All-Star", "4-time scoring champion", "Played mainly for 76ers", "Known for crossover and heart"]', '26.7 PPG, 3.7 RPG, 6.2 APG career average'),
('John', 'Stockton', '["All-time assists leader", "All-time steals leader", "Played entire career with Jazz", "Never won a championship", "10-time All-Star"]', '13.1 PPG, 2.7 RPG, 10.5 APG career average'),
('Karl', 'Malone', '["2-time MVP", "Second all-time in scoring", "Known as The Mailman", "Played mainly for Jazz", "Never won a championship"]', '25.0 PPG, 10.1 RPG, 3.6 APG career average'),
('Oscar', 'Robertson', '["1964 MVP", "Averaged triple-double for a season", "Known as The Big O", "Played for Royals and Bucks", "1 NBA championship"]', '25.7 PPG, 7.5 RPG, 9.5 APG career average'),
('Jerry', 'West', '["1969 Finals MVP on losing team", "The Logo", "14-time All-Star", "Lakers legend", "1 NBA championship"]', '27.0 PPG, 5.8 RPG, 6.7 APG career average'),
('Dwyane', 'Wade', '["3 NBA championships", "2006 Finals MVP", "Miami Heat legend", "13-time All-Star", "Flash nickname"]', '22.0 PPG, 4.7 RPG, 5.4 APG career average'),
('Kevin', 'Garnett', '["2008 NBA champion", "2004 MVP", "15-time All-Star", "Known for intensity", "The Big Ticket"]', '17.8 PPG, 10.0 RPG, 3.7 APG career average'),
('Kawhi', 'Leonard', '["2 NBA championships", "2 Finals MVPs", "2-time Defensive Player of Year", "Known as The Klaw", "Quiet superstar"]', '19.2 PPG, 6.4 RPG, 2.9 APG career average'),
('Anthony', 'Davis', '["2020 NBA champion", "8-time All-Star", "Dominant two-way player", "Plays for Lakers", "Known as AD"]', '24.1 PPG, 10.6 RPG, 2.4 BPG career average'),
('James', 'Harden', '["2018 MVP", "3-time scoring champion", "Known for step-back three", "Played for Rockets, Nets, 76ers, Clippers", "The Beard"]', '24.1 PPG, 5.6 RPG, 7.1 APG career average'),
('Russell', 'Westbrook', '["2017 MVP", "All-time triple-double leader", "9-time All-Star", "Explosive athleticism", "Played for multiple teams"]', '21.7 PPG, 7.1 RPG, 8.1 APG career average'),
('Damian', 'Lillard', '["8-time All-Star", "Trail Blazers legend", "Clutch shooter", "Known for deep threes", "Dame Time"]', '25.2 PPG, 4.2 RPG, 6.7 APG career average'),
('Joel', 'Embiid', '["2023 MVP", "7-time All-Star", "Dominant center", "Plays for 76ers", "From Cameroon"]', '27.9 PPG, 11.2 RPG, 3.6 APG career average'),
('Nikola', 'Jokic', '["3-time MVP", "2023 NBA champion", "2023 Finals MVP", "From Serbia", "Nuggets center"]', '20.9 PPG, 10.7 RPG, 6.9 APG career average'),
('Luka', 'Doncic', '["Multiple All-Star selections", "From Slovenia", "Mavericks franchise player", "Former EuroLeague MVP", "Young superstar"]', '28.7 PPG, 8.7 RPG, 8.3 APG career average'),
('Chris', 'Paul', '["12-time All-Star", "All-time assists leader among active", "Point God", "Played for multiple teams", "Never won championship"]', '17.9 PPG, 4.5 RPG, 9.4 APG career average'),
('Paul', 'Pierce', '["2008 NBA champion", "2008 Finals MVP", "Celtics legend", "10-time All-Star", "The Truth"]', '19.7 PPG, 5.6 RPG, 3.5 APG career average'),
('Ray', 'Allen', '["2 NBA championships", "All-time three-point leader before Curry", "10-time All-Star", "Hit crucial Game 6 shot in 2013", "Smooth shooter"]', '18.9 PPG, 4.1 RPG, 3.4 APG career average'),
('Clyde', 'Drexler', '["1995 NBA champion", "10-time All-Star", "Known as Clyde the Glide", "Played for Blazers and Rockets", "Hall of Famer"]', '20.4 PPG, 6.1 RPG, 5.6 APG career average'),
('Patrick', 'Ewing', '["1992 Olympic Dream Team", "11-time All-Star", "Knicks legend", "Dominant center", "Never won championship"]', '21.0 PPG, 9.8 RPG, 2.4 BPG career average'),
('Gary', 'Payton', '["1996 Defensive Player of Year", "2006 NBA champion", "The Glove", "9-time All-Star", "Elite point guard defender"]', '16.3 PPG, 3.9 RPG, 6.7 APG career average'),
('Scottie', 'Pippen', '["6 NBA championships", "7-time All-Star", "Michael Jordan''s sidekick", "Elite defender", "Bulls dynasty member"]', '16.1 PPG, 6.4 RPG, 5.2 APG career average'),
('Dennis', 'Rodman', '["5 NBA championships", "7-time rebounding champion", "2-time Defensive Player of Year", "Known for hair colors", "The Worm"]', '7.3 PPG, 13.1 RPG career average'),
('Dominique', 'Wilkins', '["9-time All-Star", "Hawks legend", "Known for dunking", "The Human Highlight Film", "Scoring champion in 1986"]', '24.8 PPG, 6.7 RPG, 2.5 APG career average');

-- ============================================
-- 3. MVP WINNERS (1956-2025, 70 entries)
-- ============================================

INSERT INTO public.mvp_winners (year, first_name, last_name, team) VALUES
(2025, 'Shai', 'Gilgeous-Alexander', 'Oklahoma City Thunder'),
(2024, 'Nikola', 'Jokic', 'Denver Nuggets'),
(2023, 'Joel', 'Embiid', 'Philadelphia 76ers'),
(2022, 'Nikola', 'Jokic', 'Denver Nuggets'),
(2021, 'Nikola', 'Jokic', 'Denver Nuggets'),
(2020, 'Giannis', 'Antetokounmpo', 'Milwaukee Bucks'),
(2019, 'Giannis', 'Antetokounmpo', 'Milwaukee Bucks'),
(2018, 'James', 'Harden', 'Houston Rockets'),
(2017, 'Russell', 'Westbrook', 'Oklahoma City Thunder'),
(2016, 'Stephen', 'Curry', 'Golden State Warriors'),
(2015, 'Stephen', 'Curry', 'Golden State Warriors'),
(2014, 'Kevin', 'Durant', 'Oklahoma City Thunder'),
(2013, 'LeBron', 'James', 'Miami Heat'),
(2012, 'LeBron', 'James', 'Miami Heat'),
(2011, 'Derrick', 'Rose', 'Chicago Bulls'),
(2010, 'LeBron', 'James', 'Cleveland Cavaliers'),
(2009, 'LeBron', 'James', 'Cleveland Cavaliers'),
(2008, 'Kobe', 'Bryant', 'Los Angeles Lakers'),
(2007, 'Dirk', 'Nowitzki', 'Dallas Mavericks'),
(2006, 'Steve', 'Nash', 'Phoenix Suns'),
(2005, 'Steve', 'Nash', 'Phoenix Suns'),
(2004, 'Kevin', 'Garnett', 'Minnesota Timberwolves'),
(2003, 'Tim', 'Duncan', 'San Antonio Spurs'),
(2002, 'Tim', 'Duncan', 'San Antonio Spurs'),
(2001, 'Allen', 'Iverson', 'Philadelphia 76ers'),
(2000, 'Shaquille', 'O''Neal', 'Los Angeles Lakers'),
(1999, 'Karl', 'Malone', 'Utah Jazz'),
(1998, 'Michael', 'Jordan', 'Chicago Bulls'),
(1997, 'Karl', 'Malone', 'Utah Jazz'),
(1996, 'Michael', 'Jordan', 'Chicago Bulls'),
(1995, 'David', 'Robinson', 'San Antonio Spurs'),
(1994, 'Hakeem', 'Olajuwon', 'Houston Rockets'),
(1993, 'Charles', 'Barkley', 'Phoenix Suns'),
(1992, 'Michael', 'Jordan', 'Chicago Bulls'),
(1991, 'Michael', 'Jordan', 'Chicago Bulls'),
(1990, 'Magic', 'Johnson', 'Los Angeles Lakers'),
(1989, 'Magic', 'Johnson', 'Los Angeles Lakers'),
(1988, 'Michael', 'Jordan', 'Chicago Bulls'),
(1987, 'Magic', 'Johnson', 'Los Angeles Lakers'),
(1986, 'Larry', 'Bird', 'Boston Celtics'),
(1985, 'Larry', 'Bird', 'Boston Celtics'),
(1984, 'Larry', 'Bird', 'Boston Celtics'),
(1983, 'Moses', 'Malone', 'Philadelphia 76ers'),
(1982, 'Moses', 'Malone', 'Houston Rockets'),
(1981, 'Julius', 'Erving', 'Philadelphia 76ers'),
(1980, 'Kareem', 'Abdul-Jabbar', 'Los Angeles Lakers'),
(1979, 'Moses', 'Malone', 'Houston Rockets'),
(1978, 'Bill', 'Walton', 'Portland Trail Blazers'),
(1977, 'Kareem', 'Abdul-Jabbar', 'Los Angeles Lakers'),
(1976, 'Kareem', 'Abdul-Jabbar', 'Los Angeles Lakers'),
(1975, 'Bob', 'McAdoo', 'Buffalo Braves'),
(1974, 'Kareem', 'Abdul-Jabbar', 'Milwaukee Bucks'),
(1973, 'Dave', 'Cowens', 'Boston Celtics'),
(1972, 'Kareem', 'Abdul-Jabbar', 'Milwaukee Bucks'),
(1971, 'Kareem', 'Abdul-Jabbar', 'Milwaukee Bucks'),
(1970, 'Willis', 'Reed', 'New York Knicks'),
(1969, 'Wes', 'Unseld', 'Baltimore Bullets'),
(1968, 'Wilt', 'Chamberlain', 'Philadelphia 76ers'),
(1967, 'Wilt', 'Chamberlain', 'Philadelphia 76ers'),
(1966, 'Wilt', 'Chamberlain', 'Philadelphia 76ers'),
(1965, 'Bill', 'Russell', 'Boston Celtics'),
(1964, 'Oscar', 'Robertson', 'Cincinnati Royals'),
(1963, 'Bill', 'Russell', 'Boston Celtics'),
(1962, 'Bill', 'Russell', 'Boston Celtics'),
(1961, 'Bill', 'Russell', 'Boston Celtics'),
(1960, 'Wilt', 'Chamberlain', 'Philadelphia Warriors'),
(1959, 'Bob', 'Pettit', 'St. Louis Hawks'),
(1958, 'Bill', 'Russell', 'Boston Celtics'),
(1957, 'Bob', 'Cousy', 'Boston Celtics'),
(1956, 'Bob', 'Pettit', 'St. Louis Hawks');


